language: python

python:
    - "2.6"
    - "2.7"

virtualenv:
  system_site_packages: true

before_install:
    - sudo apt-get install -qq python-networkx 
    - sudo apt-get install -qq python-nibabel
    - sudo apt-get install -qq python-numpy
    - sudo apt-get install -qq python-scipy
    - sudo apt-get install -qq python-traits
    - sudo apt-get install -qq python-nose
    - sudo apt-get install -qq python-nipype
    - sudo apt-get install -qq python-coverage

install:
    - python setup.py install

script:
    - python setup.py nosetests


